#ifndef _LIBC_LOGGINGX_H_
#define _LIBC_LOGGINGX_H_

#include <stdint.h>
#include <logcat/logcat.h>

enum
{
  BIONIC_EVENT_MEMCPY_BUFFER_OVERFLOW = 80100,
  BIONIC_EVENT_STRCAT_BUFFER_OVERFLOW = 80105,
  BIONIC_EVENT_MEMMOVE_BUFFER_OVERFLOW = 80110,
  BIONIC_EVENT_STRNCAT_BUFFER_OVERFLOW = 80115,
  BIONIC_EVENT_STRNCPY_BUFFER_OVERFLOW = 80120,
  BIONIC_EVENT_MEMSET_BUFFER_OVERFLOW = 80125,
  BIONIC_EVENT_STRCPY_BUFFER_OVERFLOW = 80130,
  BIONIC_EVENT_STRCAT_INTEGER_OVERFLOW = 80200,
  BIONIC_EVENT_STRNCAT_INTEGER_OVERFLOW = 80205,
  BIONIC_EVENT_RESOLVER_OLD_RESPONSE = 80300,
  BIONIC_EVENT_RESOLVER_WRONG_SERVER = 80305,
  BIONIC_EVENT_RESOLVER_WRONG_QUERY = 80310,
};

extern "C" void __fortify_chk_fail(const char *msg, uint32_t event_tag);

#endif /* _LIBC_LOGGINGX_H_ */
