#!/usr/bin/env python3
"""Generate the unified bridge symbol table from symbol.def."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


callback_pattern = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

generated_includes = r"""
#define _GNU_SOURCE

#include <arpa/inet.h>
#include <ctype.h>
#include <dirent.h>
#include <locale.h>
#include <malloc.h>
#include <math.h>
#include <netdb.h>
#include <pthread.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <wchar.h>
#include <wctype.h>

#include <sys/errno.h>
#include <sys/fcntl.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/unistd.h>

#include <patcher.h>
#include <loader.h>
#include <logcat/logcat.h>

#include <android/assetmgr.h>
#include <android/log.h>
#include <audio/provider.h>
#include <eabi.h>
#include <libc/impl/bionic/bionic.h>
#include <libc/impl/libc.h>
#include <libc/impl/pthread.h>
#include <opengl/impl/opengl.h>
#include <symbols.h>
""".strip()


def parse_definition(path: Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    symbols: dict[str, int] = {}

    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        parts = [part.strip() for part in line.split("|")]
        if len(parts) != 2 or not all(parts):
            raise ValueError(
                f"{path}:{line_number}: expected SYMBOL|CALLBACK"
            )

        symbol, callback = parts
        if callback.startswith("&"):
            callback = callback[1:].strip()
        if not callback_pattern.fullmatch(callback):
            raise ValueError(
                f"{path}:{line_number}: invalid C callback name {callback!r}"
            )
        if symbol in symbols:
            raise ValueError(
                f"{path}:{line_number}: duplicate symbol {symbol!r}; "
                f"first declared on line {symbols[symbol]}"
            )

        symbols[symbol] = line_number
        entries.append((symbol, callback))

    if not entries:
        raise ValueError(f"{path}: symbol definition is empty")
    return entries


def c_string(value: str) -> str:
    return (
        '"'
        + value.replace("\\", "\\\\").replace('"', '\\"')
        .replace("\n", "\\n")
        + '"'
    )


def generate(entries: list[tuple[str, str]], source: Path) -> str:
    entries = sorted(entries, key=lambda entry: entry[0])
    rows = "\n".join(
        f"  {{{c_string(symbol)}, (uintptr_t)&{callback}}},"
        for symbol, callback in entries
    )
    return f"""/*
 * Generated from {source.name}; do not edit this file directly.
 * Symbol count: {len(entries)}
 * The table is sorted by imported symbol for binary-search patching.
 */

{generated_includes}

static const patch_func_t __bridge_symbols[] =
{{
{rows}
}};

void loader_symbol_ref(void)
{{
  loader_register_symbol_ref(
      __bridge_symbols,
      sizeof(__bridge_symbols) / sizeof(__bridge_symbols[0]));
}}

void patch_bridge_symbols(dynalib_t *library)
{{
  patch_symbols(library, __bridge_symbols,
               sizeof(__bridge_symbols) / sizeof(__bridge_symbols[0]));
}}

uint32_t bridge_symbol_count(void)
{{
  return sizeof(__bridge_symbols) / sizeof(__bridge_symbols[0]);
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("definition", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    entries = parse_definition(args.definition)
    content = generate(entries, args.definition)
    args.output.parent.mkdir(parents=True, exist_ok=True)

    previous = (
        args.output.read_text(encoding="utf-8")
        if args.output.exists()
        else None
    )
    if previous != content:
        args.output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
